### ISSUE TITLE
Exit Code 1 when examining Podfile

### ISSUE THREAD

**Issue by dannypier** [bitrise-io/steps-repository-scanner#10]
```
Running detection scripts on brach: master
Podfile:17:in 'xctesting_pods': undefined method '/' for nil:NilClass (NoMethodError)
    from Podfile:31:in 'block (2 levels) in from_file'
    from /tmp/bitrise722231499/step_src/detectors/podfile.rb:37:in 'call'
    from /tmp/bitrise722231499/step_src/detectors/podfile.rb:37:in 'target'
    from Podfile:30:in `block in from_file'
    from /tmp/bitrise722231499/step_src/detectors/podfile.rb:17:in 'eval'
    from /tmp/bitrise722231499/step_src/detectors/podfile.rb:17:in 'block in from_file'
    from /tmp/bitrise722231499/step_src/detectors/podfile.rb:23:in 'instance_eval'
    from /tmp/bitrise722231499/step_src/detectors/podfile.rb:23:in 'initialize'
    from /tmp/bitrise722231499/step_src/detectors/podfile.rb:14:in 'new'
    from /tmp/bitrise722231499/step_src/detectors/podfile.rb:14:in 'from_file'
    from /tmp/bitrise722231499/step_src/detectors/ios.rb:33:in 'block in <main>'
    from /tmp/bitrise722231499/step_src/detectors/ios.rb:30:in 'each'
    from /tmp/bitrise722231499/step_src/detectors/ios.rb:30:in '<main>'

iOS project detected

Checking for Podfile
Podfile detected at path: Podfile
detector /tmp/bitrise722231499/step_src/detectors/ios.rb failed
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | repository-scanner@1.4.3 (exit code: 1)                      | 0.91 sec |
```

**Comment by godrei** [comment]
@dannypier Thanks for reporting, 
can you please share your podfile with us?
