### ISSUE TITLE
step_src/detectors/xamarin.rb:56:in `readlines': No such file or directory @ rb_sysopen - /bitrise/src/ReactiveUI.Platforms/ReactiveUI.Cocoa.csproj (Errno::ENOENT)

### ISSUE THREAD

**Issue by ghuntley** [bitrise-io/steps-repository-scanner#2]
Howdy Bitwise,

The open source project [ReactiveUI](http://www.reactiveui.net/) would like to move in and start using your services. However the following error occurs when configuring https://github.com/reactiveui/ReactiveUI (using ssh clone) (on master branch) into Bitwise via the "Add new app" workflow. :panda_face:

```
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
From github.com:reactiveui/ReactiveUI
 * [new branch]      Change-Xam.Mac-to-2.0 -> origin/Change-Xam.Mac-to-2.0
 * [new branch]      activation -> origin/activation
 * [new branch]      add_ireactivecommand -> origin/add_ireactivecommand
 * [new branch]      add_list_combine -> origin/add_list_combine
 * [new branch]      add_reactive_page_view_controller -> origin/add_reactive_page_view_controller
 * [new branch]      add_rx_collection_view -> origin/add_rx_collection_view
 * [new branch]      add_uitextview_binding -> origin/add_uitextview_binding
 * [new branch]      android-reactive-pageradapter -> origin/android-reactive-pageradapter
 * [new branch]      binding-enhancements -> origin/binding-enhancements
 * [new branch]      bitmaps    -> origin/bitmaps
 * [new branch]      change-log-level -> origin/change-log-level
 * [new branch]      common-version-location -> origin/common-version-location
 * [new branch]      control-fetcher-fix -> origin/control-fetcher-fix
 * [new branch]      death-to-implicit-observeons -> origin/death-to-implicit-observeons
 * [new branch]      delete-old-stuff -> origin/delete-old-stuff
 * [new branch]      derived-collection-delete-fix -> origin/derived-collection-delete-fix
 * [new branch]      derived-collection-linq -> origin/derived-collection-linq
 * [new branch]      docs       -> origin/docs
 * [new branch]      etw-logging -> origin/etw-logging
 * [new branch]      fill-in-values -> origin/fill-in-values
 * [new branch]      fix-debuglogger -> origin/fix-debuglogger
 * [new branch]      fix-ios-build -> origin/fix-ios-build
 * [new branch]      fix-monodroid -> origin/fix-monodroid
 * [new branch]      fix-winrt-mobilesample -> origin/fix-winrt-mobilesample
 * [new branch]      fix-wp8-mobilesample -> origin/fix-wp8-mobilesample
 * [new branch]      fixup_rxui_xsios_sln -> origin/fixup_rxui_xsios_sln
 * [new branch]      foo        -> origin/foo
 * [new branch]      fucking-stop-bothering-me-visual-studio -> origin/fucking-stop-bothering-me-visual-studio
 * [new branch]      ghuntley-readme-revamp -> origin/ghuntley-readme-revamp
 * [new branch]      haacked/set-test-scheduler-correctly -> origin/haacked/set-test-scheduler-correctly
 * [new branch]      ios-device-crash-investigation -> origin/ios-device-crash-investigation
 * [new branch]      issue/610  -> origin/issue/610
 * [new branch]      json-net-references -> origin/json-net-references
 * [new branch]      listadapter-observer -> origin/listadapter-observer
 * [new branch]      logging-init-crash-fix -> origin/logging-init-crash-fix
 * [new branch]      make_derived_collection_schedulable -> origin/make_derived_collection_schedulable
 * [new branch]      master     -> origin/master
 * [new branch]      no-more-getall-dependency-locator -> origin/no-more-getall-dependency-locator
 * [new branch]      no-more-scheduling -> origin/no-more-scheduling
 * [new branch]      nsview-activation -> origin/nsview-activation
 * [new branch]      obsaspropertyhelper-notifications -> origin/obsaspropertyhelper-notifications
 * [new branch]      per-binding-converter-override -> origin/per-binding-converter-override
 * [new branch]      prep-6.0-alpha -> origin/prep-6.0-alpha
 * [new branch]      race-fix   -> origin/race-fix
 * [new branch]      rdc-move-fixes-rxui4 -> origin/rdc-move-fixes-rxui4
 * [new branch]      reactive.input -> origin/reactive.input
 * [new branch]      readthedocs -> origin/readthedocs
 * [new branch]      recursive-activation -> origin/recursive-activation
 * [new branch]      rxcoll-must-be-scheduled -> origin/rxcoll-must-be-scheduled
 * [new branch]      rxui-net40 -> origin/rxui-net40
 * [new branch]      rxui4      -> origin/rxui4
 * [new branch]      rxui5-master -> origin/rxui5-master
 * [new branch]      rxui5-validation -> origin/rxui5-validation
 * [new branch]      rxui6-master -> origin/rxui6-master
 * [new branch]      rxui7-master -> origin/rxui7-master
 * [new branch]      support_string_headers -> origin/support_string_headers
 * [new branch]      uap        -> origin/uap
 * [new branch]      use-splat  -> origin/use-splat
 * [new branch]      whenany-collections -> origin/whenany-collections
 * [new branch]      winrt-tests -> origin/winrt-tests
 * [new branch]      xaml-memleaks -> origin/xaml-memleaks
 * [new branch]      zip-test   -> origin/zip-test
 * [new branch]      zip-test2  -> origin/zip-test2
 * [new tag]         1.2.0.0    -> 1.2.0.0
 * [new tag]         1.3.0.0    -> 1.3.0.0
 * [new tag]         1.4.0.0    -> 1.4.0.0
 * [new tag]         1.4.1.0    -> 1.4.1.0
 * [new tag]         2.0.0.0    -> 2.0.0.0
 * [new tag]         2.0.0.0-pre -> 2.0.0.0-pre
 * [new tag]         2.0.0.1    -> 2.0.0.1
 * [new tag]         2.0.0.2    -> 2.0.0.2
 * [new tag]         2.1.0.0    -> 2.1.0.0
 * [new tag]         2.1.0.1    -> 2.1.0.1
 * [new tag]         2.2.0.0    -> 2.2.0.0
 * [new tag]         2.2.0.0-pre -> 2.2.0.0-pre
 * [new tag]         2.2.1.0    -> 2.2.1.0
 * [new tag]         2.2.1.0-pre -> 2.2.1.0-pre
 * [new tag]         2.3.0.0    -> 2.3.0.0
 * [new tag]         2.3.0.0-pre -> 2.3.0.0-pre
 * [new tag]         2.3.2.0    -> 2.3.2.0
 * [new tag]         2.4.0.0    -> 2.4.0.0
 * [new tag]         2.4.5.0    -> 2.4.5.0
 * [new tag]         2.5.0.0    -> 2.5.0.0
 * [new tag]         2.5.1      -> 2.5.1
 * [new tag]         2.5.2      -> 2.5.2
 * [new tag]         3.0.0      -> 3.0.0
 * [new tag]         3.1.0      -> 3.1.0
 * [new tag]         3.1.1      -> 3.1.1
 * [new tag]         3.1.2      -> 3.1.2
 * [new tag]         3.1.3      -> 3.1.3
 * [new tag]         3.2.0      -> 3.2.0
 * [new tag]         4.0.0      -> 4.0.0
 * [new tag]         4.0.1      -> 4.0.1
 * [new tag]         4.0.2      -> 4.0.2
 * [new tag]         4.0.3      -> 4.0.3
 * [new tag]         4.1.0      -> 4.1.0
 * [new tag]         4.2.0      -> 4.2.0
 * [new tag]         4.2.1      -> 4.2.1
 * [new tag]         4.2.2      -> 4.2.2
 * [new tag]         4.3.0      -> 4.3.0
 * [new tag]         4.3.2      -> 4.3.2
 * [new tag]         4.4.0      -> 4.4.0
 * [new tag]         4.4.1      -> 4.4.1
 * [new tag]         4.4.2      -> 4.4.2
 * [new tag]         4.4.3      -> 4.4.3
 * [new tag]         4.5.0      -> 4.5.0
 * [new tag]         4.6.0      -> 4.6.0
 * [new tag]         4.6.1      -> 4.6.1
 * [new tag]         4.6.2      -> 4.6.2
 * [new tag]         4.6.3      -> 4.6.3
 * [new tag]         4.6.4      -> 4.6.4
 * [new tag]         4.6.5      -> 4.6.5
 * [new tag]         5.0.0.20130424-alpha -> 5.0.0.20130424-alpha
 * [new tag]         5.0.1      -> 5.0.1
 * [new tag]         5.1.0      -> 5.1.0
 * [new tag]         5.1.2      -> 5.1.2
 * [new tag]         5.2.0      -> 5.2.0
 * [new tag]         5.3.0      -> 5.3.0
 * [new tag]         5.4.0      -> 5.4.0
 * [new tag]         5.5.0      -> 5.5.0
 * [new tag]         5.5.1      -> 5.5.1
 * [new tag]         5.99.0     -> 5.99.0
 * [new tag]         5.99.1     -> 5.99.1
 * [new tag]         5.99.2     -> 5.99.2
 * [new tag]         5.99.3     -> 5.99.3
 * [new tag]         5.99.4     -> 5.99.4
 * [new tag]         5.99.5     -> 5.99.5
 * [new tag]         5.99.6     -> 5.99.6
 * [new tag]         6.0.0      -> 6.0.0
 * [new tag]         6.0.1      -> 6.0.1
 * [new tag]         6.0.2      -> 6.0.2
 * [new tag]         6.0.3      -> 6.0.3
 * [new tag]         6.0.4      -> 6.0.4
 * [new tag]         6.0.5      -> 6.0.5
 * [new tag]         6.0.6      -> 6.0.6
 * [new tag]         6.0.7      -> 6.0.7
 * [new tag]         6.1.0      -> 6.1.0
 * [new tag]         6.2.0      -> 6.2.0
 * [new tag]         6.2.1      -> 6.2.1
 * [new tag]         6.3.0      -> 6.3.0
 * [new tag]         6.3.1      -> 6.3.1
 * [new tag]         6.4.0      -> 6.4.0
 * [new tag]         6.4.0.1    -> 6.4.0.1
 * [new tag]         6.5.0      -> 6.5.0
Branch master set up to track remote branch master from origin.
Already on 'master'
Clone Is Success?: true
 (i) Removing private key file: /root/.ssh/bitrise
rm: invalid option -- 'P'
Try 'rm --help' for more information.
|                                                                              |
+----+--------------------------------------------------------------+----------+
| ✅  | Git Clone Repository                                         | 5.6 sec  |
+----+--------------------------------------------------------------+----------+
                                          ▼
INFO[00:24:13] Step info not found in StepLib (https://github.com/bitrise-io/bitrise-steplib.git) -- Updating ... 
INFO[00:24:13] [STEPMAN] - Update                           
From https://github.com/bitrise-io/bitrise-steplib
   9bd4e1d..6f168d8  master     -> origin/master
Updating 9bd4e1d..6f168d8
Fast-forward
 steps/android-sdk-update/1.0.1/step.yml            |  73 +++++++
 steps/appaloosa/1.1.0/step.yml                     | 133 ++++++++++++
 steps/bitrise-artifact-deploy/step-info.yml        |   3 +
 steps/bitrise-ios-deploy/step-info.yml             |   3 +
 steps/calabash-android-uitest/0.9.0/step.yml       |  35 ++++
 steps/calabash-android-uitest/assets/icon.svg      |  38 ++++
 steps/calabash-ios-uitest/0.9.0/step.yml           |  52 +++++
 steps/calabash-ios-uitest/assets/icon.svg          |  33 +++
 steps/carthage/1.0.5/step.yml                      |  77 +++++++
 .../1.4.0/step.yml                                 |  85 ++++++++
 steps/deploy-to-bitrise-io/1.1.0/step.yml          | 127 ++++++++++++
 steps/deploy-to-bitrise-io/1.2.0/step.yml          | 127 ++++++++++++
 steps/deploy-to-bitrise-io/1.2.1/step.yml          | 127 ++++++++++++
 steps/deploy-to-bitrise-io/1.2.2/step.yml          | 127 ++++++++++++
 .../deploy-to-itunesconnect-deliver/2.2.1/step.yml | 116 +++++++++++
 .../2.1.1/step.yml                                 |  89 ++++++++
 steps/fastlane/2.1.1/step.yml                      |  44 ++++
 steps/flowdock/0.1.1/step.yml                      |  39 ++++
 steps/flowdock/assets/icon.svg                     |  12 ++
 steps/git-tag/1.0.0/step.yml                       |  40 ++++
 steps/google-play-deploy/0.9.0/step.yml            |  70 +++++++
 steps/gradle-runner/1.2.0/step.yml                 | 104 ++++++++++
 steps/hockeyapp-deploy-android/0.9.0/step.yml      | 222 ++++++++++++++++++++
 steps/hockeyapp-deploy/2.2.0/step.yml              | 230 +++++++++++++++++++++
 steps/nuget-restore/0.9.0/step.yml                 |  26 +++
 steps/nuget-restore/assets/icon.svg                | 158 ++++++++++++++
 steps/repository-scanner/1.2.0/step.yml            |  59 ++++++
 steps/repository-scanner/1.3.0/step.yml            |  62 ++++++
 steps/sign-apk/0.9.1/step.yml                      |  64 ++++++
 steps/sign-apk/assets/icon.svg                     |  29 +++
 steps/start-android-emulator/0.9.2/step.yml        |  38 ++++
 steps/start-android-emulator/0.9.3/step.yml        |  38 ++++
 steps/start-android-emulator/0.9.4/step.yml        |  38 ++++
 steps/xamarin-android-test/0.9.0/step.yml          |  77 +++++++
 steps/xamarin-android-test/0.9.1/step.yml          |  77 +++++++
 steps/xamarin-android-test/assets/icon.svg         |  60 ++++++
 steps/xamarin-builder/0.9.0/step.yml               |  50 +++++
 steps/xamarin-builder/assets/icon.svg              |  16 ++
 steps/xamarin-components-restore/0.9.0/step.yml    |  26 +++
 steps/xamarin-components-restore/assets/icon.svg   |  58 ++++++
 steps/xamarin-ios-test/0.9.0/step.yml              |  99 +++++++++
 steps/xamarin-ios-test/0.9.1/step.yml              |  99 +++++++++
 steps/xamarin-ios-test/0.9.2/step.yml              |  99 +++++++++
 steps/xamarin-ios-test/0.9.3/step.yml              |  99 +++++++++
 steps/xamarin-ios-test/assets/icon.svg             |  30 +++
 .../xamarin-test-cloud-for-android/0.9.0/step.yml  | 166 +++++++++++++++
 .../xamarin-test-cloud-for-android/assets/icon.svg |  60 ++++++
 .../0.9.0/step.yml                                 | 105 ++++++++++
 .../0.9.1/step.yml                                 | 105 ++++++++++
 .../assets/icon.svg                                |  40 ++++
 .../0.9.0/step.yml                                 | 120 +++++++++++
 .../0.9.1/step.yml                                 | 113 ++++++++++
 .../assets/icon.svg                                |  35 ++++
 steps/xamarin-test-cloud-for-ios/0.9.0/step.yml    | 156 ++++++++++++++
 steps/xamarin-test-cloud-for-ios/0.9.1/step.yml    | 156 ++++++++++++++
 steps/xamarin-test-cloud-for-ios/assets/icon.svg   |  30 +++
 steps/xamarin-user-management/0.9.0/step.yml       |  56 +++++
 steps/xamarin-user-management/0.9.1/step.yml       |  55 +++++
 steps/xamarin-user-management/assets/icon.svg      |  54 +++++
 steps/xcode-analyze/1.4.0/step.yml                 |  99 +++++++++
 steps/xcode-analyze/1.4.1/step.yml                 |  99 +++++++++
 steps/xcode-archive/1.5.0/step.yml                 | 148 +++++++++++++
 steps/xcode-archive/1.5.1/step.yml                 | 148 +++++++++++++
 steps/xcode-archive/1.5.2/step.yml                 | 148 +++++++++++++
 steps/xcode-test-mac/1.0.0/step.yml                |  77 +++++++
 steps/xcode-test-mac/1.0.1/step.yml                |  77 +++++++
 steps/xcode-test-mac/1.0.2/step.yml                |  77 +++++++
 steps/xcode-test-mac/1.0.3/step.yml                |  74 +++++++
 steps/xcode-test/1.8.0/step.yml                    | 136 ++++++++++++
 69 files changed, 5642 insertions(+)
 create mode 100644 steps/android-sdk-update/1.0.1/step.yml
 create mode 100644 steps/appaloosa/1.1.0/step.yml
 create mode 100644 steps/bitrise-artifact-deploy/step-info.yml
 create mode 100644 steps/bitrise-ios-deploy/step-info.yml
 create mode 100644 steps/calabash-android-uitest/0.9.0/step.yml
 create mode 100644 steps/calabash-android-uitest/assets/icon.svg
 create mode 100644 steps/calabash-ios-uitest/0.9.0/step.yml
 create mode 100644 steps/calabash-ios-uitest/assets/icon.svg
 create mode 100644 steps/carthage/1.0.5/step.yml
 create mode 100644 steps/certificate-and-profile-installer/1.4.0/step.yml
 create mode 100644 steps/deploy-to-bitrise-io/1.1.0/step.yml
 create mode 100644 steps/deploy-to-bitrise-io/1.2.0/step.yml
 create mode 100644 steps/deploy-to-bitrise-io/1.2.1/step.yml
 create mode 100644 steps/deploy-to-bitrise-io/1.2.2/step.yml
 create mode 100644 steps/deploy-to-itunesconnect-deliver/2.2.1/step.yml
 create mode 100644 steps/deploy-to-itunesconnect-shenzhen/2.1.1/step.yml
 create mode 100644 steps/fastlane/2.1.1/step.yml
 create mode 100644 steps/flowdock/0.1.1/step.yml
 create mode 100644 steps/flowdock/assets/icon.svg
 create mode 100644 steps/git-tag/1.0.0/step.yml
 create mode 100644 steps/google-play-deploy/0.9.0/step.yml
 create mode 100644 steps/gradle-runner/1.2.0/step.yml
 create mode 100644 steps/hockeyapp-deploy-android/0.9.0/step.yml
 create mode 100644 steps/hockeyapp-deploy/2.2.0/step.yml
 create mode 100644 steps/nuget-restore/0.9.0/step.yml
 create mode 100644 steps/nuget-restore/assets/icon.svg
 create mode 100644 steps/repository-scanner/1.2.0/step.yml
 create mode 100644 steps/repository-scanner/1.3.0/step.yml
 create mode 100644 steps/sign-apk/0.9.1/step.yml
 create mode 100644 steps/sign-apk/assets/icon.svg
 create mode 100644 steps/start-android-emulator/0.9.2/step.yml
 create mode 100644 steps/start-android-emulator/0.9.3/step.yml
 create mode 100644 steps/start-android-emulator/0.9.4/step.yml
 create mode 100644 steps/xamarin-android-test/0.9.0/step.yml
 create mode 100644 steps/xamarin-android-test/0.9.1/step.yml
 create mode 100644 steps/xamarin-android-test/assets/icon.svg
 create mode 100644 steps/xamarin-builder/0.9.0/step.yml
 create mode 100644 steps/xamarin-builder/assets/icon.svg
 create mode 100644 steps/xamarin-components-restore/0.9.0/step.yml
 create mode 100644 steps/xamarin-components-restore/assets/icon.svg
 create mode 100644 steps/xamarin-ios-test/0.9.0/step.yml
 create mode 100644 steps/xamarin-ios-test/0.9.1/step.yml
 create mode 100644 steps/xamarin-ios-test/0.9.2/step.yml
 create mode 100644 steps/xamarin-ios-test/0.9.3/step.yml
 create mode 100644 steps/xamarin-ios-test/assets/icon.svg
 create mode 100644 steps/xamarin-test-cloud-for-android/0.9.0/step.yml
 create mode 100644 steps/xamarin-test-cloud-for-android/assets/icon.svg
 create mode 100644 steps/xamarin-test-cloud-for-calabash-android/0.9.0/step.yml
 create mode 100644 steps/xamarin-test-cloud-for-calabash-android/0.9.1/step.yml
 create mode 100644 steps/xamarin-test-cloud-for-calabash-android/assets/icon.svg
 create mode 100644 steps/xamarin-test-cloud-for-calabash-ios/0.9.0/step.yml
 create mode 100644 steps/xamarin-test-cloud-for-calabash-ios/0.9.1/step.yml
 create mode 100644 steps/xamarin-test-cloud-for-calabash-ios/assets/icon.svg
 create mode 100644 steps/xamarin-test-cloud-for-ios/0.9.0/step.yml
 create mode 100644 steps/xamarin-test-cloud-for-ios/0.9.1/step.yml
 create mode 100644 steps/xamarin-test-cloud-for-ios/assets/icon.svg
 create mode 100644 steps/xamarin-user-management/0.9.0/step.yml
 create mode 100644 steps/xamarin-user-management/0.9.1/step.yml
 create mode 100644 steps/xamarin-user-management/assets/icon.svg
 create mode 100644 steps/xcode-analyze/1.4.0/step.yml
 create mode 100644 steps/xcode-analyze/1.4.1/step.yml
 create mode 100644 steps/xcode-archive/1.5.0/step.yml
 create mode 100644 steps/xcode-archive/1.5.1/step.yml
 create mode 100644 steps/xcode-archive/1.5.2/step.yml
 create mode 100644 steps/xcode-test-mac/1.0.0/step.yml
 create mode 100644 steps/xcode-test-mac/1.0.1/step.yml
 create mode 100644 steps/xcode-test-mac/1.0.2/step.yml
 create mode 100644 steps/xcode-test-mac/1.0.3/step.yml
 create mode 100644 steps/xcode-test/1.8.0/step.yml
INFO[00:24:13] [STEPMAN] - Updated                          
+------------------------------------------------------------------------------+
| (2) repository-scanner@1.3.0                                                 |
+------------------------------------------------------------------------------+
| id: repository-scanner                                                       |
| version: 1.3.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2015-12-23T00:24:14Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Scanning only: master
==============================
Switching to origin/master...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Running detection scripts
/tmp/bitrise659036591/step_src/detectors/xamarin.rb:56:in `readlines': No such file or directory @ rb_sysopen - /bitrise/src/ReactiveUI.Platforms/ReactiveUI.Cocoa.csproj (Errno::ENOENT)
    from /tmp/bitrise659036591/step_src/detectors/xamarin.rb:56:in `get_xamarin_ios_api_and_configs'
    from /tmp/bitrise659036591/step_src/detectors/xamarin.rb:125:in `block (2 levels) in <main>'
    from /tmp/bitrise659036591/step_src/detectors/xamarin.rb:121:in `each'
    from /tmp/bitrise659036591/step_src/detectors/xamarin.rb:121:in `block in <main>'
    from /tmp/bitrise659036591/step_src/detectors/xamarin.rb:106:in `each'
    from /tmp/bitrise659036591/step_src/detectors/xamarin.rb:106:in `<main>'
ERRO[00:24:15] Step (repository-scanner@1.3.0) failed, error: (exit status 1) 
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | repository-scanner@1.3.0 (exit code: 1)                      | 2.1 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-repository-scanner/issues |
| Source: https://github.com/bitrise-io/steps-repository-scanner               |
+----+--------------------------------------------------------------+----------+
+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+----+--------------------------------------------------------------+----------+
|    | title                                                        | time (s) |
+----+--------------------------------------------------------------+----------+
| ✅  | Activate App SSH key                                         | 0.93 sec |
+----+--------------------------------------------------------------+----------+
| ✅  | Git Clone Repository                                         | 5.6 sec  |
+----+--------------------------------------------------------------+----------+
| 🚫  | repository-scanner@1.3.0 (exit code: 1)                      | 2.1 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-repository-scanner/issues |
| Source: https://github.com/bitrise-io/steps-repository-scanner               |
+----+--------------------------------------------------------------+----------+
| Total runtime: 8.7 sec                                                       |
+------------------------------------------------------------------------------+
FATA[00:24:15] Error:  [BITRISE_CLI] - Workflow FINISHED but a couple of steps failed - Ouch 
2015/12/23 00:24:24 Failed to run, error: exit status 1
```

**Comment by birmacher** [comment]
We've just rolled out a fix (1.3.1) that solves this issue, so I'm closing the ticket. If you hit the same problem again please just reopen it and we'll take a look.

Thanks for notifying us!
